
package actionbazaar.buslogic;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0.1-07/28/2007 11:24 PM(bt)-BEA
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "BidException", targetNamespace = "http://actionbazaar.com/xml")
public class BidException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BidException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BidException_Exception(String message, BidException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public BidException_Exception(String message, BidException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: actionbazaar.buslogic.BidException
     */
    public BidException getFaultInfo() {
        return faultInfo;
    }

}
