
package actionbazaar.buslogic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0.1-07/28/2007 11:24 PM(bt)-BEA
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PlaceBid", targetNamespace = "http://actionbazaar.com/xml")
public interface PlaceBid {


    /**
     * 
     * @param arg1
     * @param arg0
     * @param arg2
     * @return
     *     returns java.lang.Long
     * @throws BidException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBid", targetNamespace = "http://actionbazaar.com/xml", className = "actionbazaar.buslogic.AddBid")
    @ResponseWrapper(localName = "addBidResponse", targetNamespace = "http://actionbazaar.com/xml", className = "actionbazaar.buslogic.AddBidResponse")
    public Long addBid(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Double arg2)
        throws BidException_Exception
    ;

}
