
package actionbazaar.buslogic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0.1-07/28/2007 11:24 PM(bt)-BEA
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PlaceBidService", targetNamespace = "http://actionbazaar.com/xml", wsdlLocation = "http://localhost:7001/PlaceBidBean/PlaceBidBeanService?wsdl")
public class PlaceBidService
    extends Service
{

    private final static URL PLACEBIDSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7001/PlaceBidBean/PlaceBidBeanService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PLACEBIDSERVICE_WSDL_LOCATION = url;
    }

    public PlaceBidService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlaceBidService() {
        super(PLACEBIDSERVICE_WSDL_LOCATION, new QName("http://actionbazaar.com/xml", "PlaceBidService"));
    }

    /**
     * 
     * @return
     *     returns PlaceBid
     */
    @WebEndpoint(name = "PlaceBidPort")
    public PlaceBid getPlaceBidPort() {
        return (PlaceBid)super.getPort(new QName("http://actionbazaar.com/xml", "PlaceBidPort"), PlaceBid.class);
    }

}
