CREATE TABLE SUPPLIER_DETAILS
(
SUPPLIER_ID NUMBER(15) NOT NULL PRIMARY KEY,
SUPPLIER_NAME VARCHAR2(120),
CREATED_BY VARCHAR2(60) NOT NULL,
CREATION_DATE DATE NOT NULL,
LAST_UPDATED_BY VARCHAR2(60) NOT NULL,
LAST_UPDATE_DATE DATE NOT NULL,
OBJECT_VERSION_ID NUMBER(15) NOT NULL
CONTACT_ID NUMBER(15) NOT NULL
)

CREATE TABLE SUPPLIER_CONTACTS
(
CONTACT_ID NUMBER(15) NOT NULL,
EMAIL VARCHAR2(40),
PHONE VARCHAR2(15) NOT NULL,
STREET1 VARCHAR2(15) ,
STREET2 VARCHAR2(15) ,
CITY VARCHAR2(15) ,
STATE VARCHAR2(15) ,
POSTAL_CODE VARCHAR2(15) ,
COUNTRY VARCHAR2(15) ,

)


CREATE TABLE SUPPLIER_PRODUCTS
(
CONTACT_ID NUMBER(15) NOT NULL,
EMAIL VARCHAR2(40),
PHONE VARCHAR2(15) NOT NULL,
STREET1 VARCHAR2(15) ,
STREET2 VARCHAR2(15) ,
CITY VARCHAR2(15) ,
STATE VARCHAR2(15) ,
POSTAL_CODE VARCHAR2(15) ,
COUNTRY VARCHAR2(15) ,
)
